packages:
  - 'crates/node'
  - 'crates/node/npm/*'
  - 'packages/*'
  - 'playgrounds/*'
  - 'integrations'

catalog:
  '@types/node': ^20.19.0
  prettier: 3.5.0
  vite: ^7.0.0
  tailwindcss: ^4.0.0
  '@tailwindcss/vite': ^4.0.0
  '@tailwindcss/node': ^4.0.0
  '@tailwindcss/oxide': ^4.0.0